### ISSUE TITLE
Tests de performances des cartes

### ISSUE THREAD

**Issue by GwenaelMoreau** [delisea/R-Montagne#6]

**Comment by Hugo-AF** [comment]
La balise peut-elle être en permanence allumée ?

**Comment by Hugo-AF** [comment]
En pleine utilisation, ce serait à peine plus d'1j, suffisant pour garder balise allumée en permanence avec panneau solaire, dans le cadre du projet. Si implémenté en vrai, on recommenderait une batterie plus importante.
1j en utilisant le capteur à plein tarif permet de ne pas avoir à se faure de soucis pour les capteurs utilisateurs dont la consommation est plus régulée
